[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Prerender.io redirect for crawlers
[[redirects]]
  from = "/*"
  to = "https://service.prerender.io/https://cafeaddaa.netlify.app/:splat"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawler*", "*spider*", "*crawling*", "facebookexternalhit*", "*Prerender*"]}
  force = true

# Client-side routing fallback for regular users
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
