[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Prerender.io configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Enable prerendering for crawlers
[[edge_functions]]
  function = "prerender"
  path = "/*"

# Redirect rules for Prerender.io
[[redirects]]
  from = "/*"
  to = "https://service.prerender.io/https://tastecraft.netlify.app/:splat"
  status = 200
  conditions = {Role = ["prerender"]}
  force = true

# Client-side routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
